Search with aggs
Hunter2065/ChewiTest pull request #2
Opened 2021-08-17 16:56 UTC by Hunter2065

search by aggs for showing statistic of cities, it looks like that:
![Screenshot 2021-08-17 at 19 54 44](https://user-images.githubusercontent.com/49816584/129768551-c853850d-d42f-4b3a-8473-6ca71d7e503a.png)

2021-08-17 17:03 UTC, igorkasyanchuk requested changes

2021-08-17 17:03 UTC, igorkasyanchuk commented on app/helpers/application_helper.rb
> +    @cities_aggs = UsersSearch.new.search.aggs
а це що за прикол, кожен раз ти робиш пошук? це не гуд, пошук і агрегації мають працювати разом на одних і тих самих квері
на розетці якщо ти щось шукаєш то ти бачиш агрегації тільки ті які відносяться до пошуку а не 1000000 категорій

2021-08-17 17:03 UTC, igorkasyanchuk commented on app/searches/users_search.rb
> +      .aggs(aggregation_condition)
зроби клас який робить 1)і пошук  2) робить агрегації, і забери той код з хелпера де воно викликається

має це все в контролері юзатись В СЕРЧІ

на індексі немає бути ніяких агрегацій чи пошуків

2021-08-17 17:03 UTC, igorkasyanchuk commented on app/views/shared/_form.html.erb
> +  <% clean_keys(object).each do |key| %>
от тут твій хелпер викликає запити 1000 раз до еластіка, ну типу скільки міст стільки раз І ЦЕ НЕ ПРАВИЛЬНО

тільки 2 запита має бути до еластіка - пошук і агрегації

2021-08-17 17:03 UTC, igorkasyanchuk commented on spec/views/cities/edit.html.erb_spec.rb
> +  pending "add some examples to (or delete) #{__FILE__}"
видали

2021-08-17 17:03 UTC, igorkasyanchuk commented on spec/views/cities/index.html.erb_spec.rb
> +  pending "add some examples to (or delete) #{__FILE__}"
видали

2021-08-17 17:03 UTC, igorkasyanchuk commented on spec/models/city_spec.rb
> +  pending "add some examples to (or delete) #{__FILE__}"
де тест

2021-08-17 17:06 UTC, Hunter2065 commented on app/controllers/users_controller.rb
> +    @cities = City.all
окс, круть, за це не подувмав, виправлю

2021-08-17 17:09 UTC, Hunter2065 commented on spec/views/cities/index.html.erb_spec.rb
> +  pending "add some examples to (or delete) #{__FILE__}"
fixed

2021-08-17 17:13 UTC, Hunter2065 commented on app/assets/stylesheets/cities.scss
> +// Place all the styles related to the cities controller here.
also fixed

2021-08-17 17:13 UTC, Hunter2065 commented on spec/views/cities/edit.html.erb_spec.rb
> +  pending "add some examples to (or delete) #{__FILE__}"
also fixed

2021-08-18 07:10 UTC, Hunter2065 commented on spec/models/city_spec.rb
> +  pending "add some examples to (or delete) #{__FILE__}"
уже написав)

2021-08-18 07:47 UTC, Hunter2065 commented on app/helpers/application_helper.rb
> +    @cities_aggs['cities']['buckets'].each do |hash|
okay, thanks

2021-08-18 13:04 UTC, Hunter2065 commented on app/controllers/users_controller.rb
> +    @cities = City.all
момент зрозумів, виправив)

2021-08-18 13:05 UTC, Hunter2065 commented on app/helpers/application_helper.rb
> +    @cities_aggs = UsersSearch.new.search.aggs
теж готово

2021-08-18 13:05 UTC, Hunter2065 commented on app/searches/users_search.rb
> +      .aggs(aggregation_condition)
теж зробив)

2021-08-18 13:06 UTC, Hunter2065 commented on app/views/shared/_form.html.erb
> +  <% clean_keys(object).each do |key| %>
теж виправив)

2021-08-19 08:06 UTC, igorkasyanchuk commented on app/helpers/application_helper.rb
> +    array_of_values = model_obj.attributes.except('created_at',
нащо цей метод?

2021-08-19 08:15 UTC, Hunter2065 commented on app/helpers/application_helper.rb
> +    array_of_values = model_obj.attributes.except('created_at',
видалив)

2021-08-19 10:38 UTC, merged